#############################################################################
# Makefile for building: Coocorrencia
# Generated by qmake (2.01a) (Qt 4.8.6) on: qui out 2 15:53:41 2014
# Project:  ../Coocorrencia/Coocorrencia.pro
# Template: app
# Command: /opt/Trolltech/Qt-4.8.6/bin/qmake -spec /opt/Trolltech/Qt-4.8.6/mkspecs/linux-g++ -o Makefile ../Coocorrencia/Coocorrencia.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/Trolltech/Qt-4.8.6/mkspecs/linux-g++ -I../Coocorrencia -I/opt/Trolltech/Qt-4.8.6/include/QtCore -I/opt/Trolltech/Qt-4.8.6/include -I/usr/local/cuda/include -I../Nvidia/OpenCL/common/inc -I../Nvidia/shared/inc -I. -I../Coocorrencia -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Trolltech/Qt-4.8.6/lib
LIBS          = $(SUBLIBS)  -L/opt/Trolltech/Qt-4.8.6/lib -L/home/local1/pedrock/Documentos/Coocorrencia/../../../../../usr/local/cuda/lib64/ -lOpenCL -L/home/local1/pedrock/Documentos/Coocorrencia/../Nvidia/OpenCL/common/lib/ -loclUtil_x86_64 -L/home/local1/pedrock/Documentos/Coocorrencia/../Nvidia/shared/lib/ -lshrutil_x86_64 -lQtCore -L/opt/Trolltech/Qt-4.8.6/lib -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Trolltech/Qt-4.8.6/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Coocorrencia/main.cpp \
		../Coocorrencia/vetor.cpp \
		../Coocorrencia/coocorrencia.cpp \
		../Coocorrencia/operacoes.cpp qrc_ocorrencia.cpp
OBJECTS       = main.o \
		vetor.o \
		coocorrencia.o \
		operacoes.o \
		qrc_ocorrencia.o
DIST          = /opt/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/release.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/shared.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/unix/thread.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/moc.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/resources.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/uic.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/yacc.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/lex.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf \
		../Coocorrencia/Coocorrencia.pro
QMAKE_TARGET  = Coocorrencia
DESTDIR       = 
TARGET        = Coocorrencia

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /home/local1/pedrock/Documentos/Coocorrencia/../Nvidia/OpenCL/common/lib/liboclUtil_x86_64.a /home/local1/pedrock/Documentos/Coocorrencia/../Nvidia/shared/lib/libshrutil_x86_64.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Coocorrencia/Coocorrencia.pro  /opt/Trolltech/Qt-4.8.6/mkspecs/linux-g++/qmake.conf /opt/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/release.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/shared.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/unix/thread.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/moc.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/resources.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/uic.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/yacc.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/lex.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf \
		/opt/Trolltech/Qt-4.8.6/lib/libQtCore.prl
	$(QMAKE) -spec /opt/Trolltech/Qt-4.8.6/mkspecs/linux-g++ -o Makefile ../Coocorrencia/Coocorrencia.pro
/opt/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/release.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/shared.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/unix/thread.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/moc.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/resources.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/uic.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/yacc.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/lex.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf:
/opt/Trolltech/Qt-4.8.6/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/Trolltech/Qt-4.8.6/mkspecs/linux-g++ -o Makefile ../Coocorrencia/Coocorrencia.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Coocorrencia1.0.0 || $(MKDIR) .tmp/Coocorrencia1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Coocorrencia1.0.0/ && $(COPY_FILE) --parents ../Coocorrencia/vetor.h ../Coocorrencia/coocorrencia.h ../Coocorrencia/operacoes.h .tmp/Coocorrencia1.0.0/ && $(COPY_FILE) --parents ../Coocorrencia/ocorrencia.qrc .tmp/Coocorrencia1.0.0/ && $(COPY_FILE) --parents ../Coocorrencia/main.cpp ../Coocorrencia/vetor.cpp ../Coocorrencia/coocorrencia.cpp ../Coocorrencia/operacoes.cpp .tmp/Coocorrencia1.0.0/ && (cd `dirname .tmp/Coocorrencia1.0.0` && $(TAR) Coocorrencia1.0.0.tar Coocorrencia1.0.0 && $(COMPRESS) Coocorrencia1.0.0.tar) && $(MOVE) `dirname .tmp/Coocorrencia1.0.0`/Coocorrencia1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Coocorrencia1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all: qrc_ocorrencia.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ocorrencia.cpp
qrc_ocorrencia.cpp: ../Coocorrencia/ocorrencia.qrc \
		ocorrencia.cl
	/opt/Trolltech/Qt-4.8.6/bin/rcc -name ocorrencia ../Coocorrencia/ocorrencia.qrc -o qrc_ocorrencia.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.o: ../Coocorrencia/main.cpp /usr/local/cuda/include/CL/cl.h \
		/usr/local/cuda/include/CL/cl_platform.h \
		/usr/local/cuda/include/CL/opencl.h \
		/usr/local/cuda/include/CL/cl_gl.h \
		/usr/local/cuda/include/CL/cl_gl_ext.h \
		/usr/local/cuda/include/CL/cl_ext.h \
		../Nvidia/OpenCL/common/inc/oclUtils.h \
		../Nvidia/OpenCL/common/inc/shrUtils.h \
		../Coocorrencia/coocorrencia.h \
		../Coocorrencia/vetor.h \
		../Coocorrencia/operacoes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Coocorrencia/main.cpp

vetor.o: ../Coocorrencia/vetor.cpp ../Coocorrencia/vetor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vetor.o ../Coocorrencia/vetor.cpp

coocorrencia.o: ../Coocorrencia/coocorrencia.cpp ../Coocorrencia/coocorrencia.h \
		../Coocorrencia/vetor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coocorrencia.o ../Coocorrencia/coocorrencia.cpp

operacoes.o: ../Coocorrencia/operacoes.cpp ../Coocorrencia/operacoes.h \
		../Coocorrencia/coocorrencia.h \
		../Coocorrencia/vetor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o operacoes.o ../Coocorrencia/operacoes.cpp

qrc_ocorrencia.o: qrc_ocorrencia.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ocorrencia.o qrc_ocorrencia.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

